name: GitHub-Profile-Summary-Cards

on:
  schedule: # Chạy tự động 24h một lần
    - cron: "0 0 * * *"
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write # Cấp quyền ghi file
    steps:
      - uses: actions/checkout@v3
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
